### ISSUE TITLE
Smoke material

### ISSUE THREAD

**Issue by Kefta** [Kefta/GSWeapons#20]

**Comment by Kefta** [comment]
CS:S particle name clashes with HL2's. No way to work around this

**Comment by MinIsMin** [comment]
What will you do? Let the user decide which to use?

**Comment by Kefta** [comment]
They will have to manually drag in the CS:S version to an addon. It's a mounting issue with Garry's Mod, and since particle material names are hardcoded in the engine, there's no way to fix it.
