### ISSUE TITLE
Add CapabilitiesGet and ObjectCaps support

### ISSUE THREAD

**Issue by Kefta** [Kefta/GSWeapons#66]
And weapon proficiency

**Comment by MinIsMin** [comment]
You mean something like skills?

**Comment by Kefta** [comment]
http://wiki.garrysmod.com/page/Enums/WEAPON_PROFICIENCY
http://wiki.garrysmod.com/page/WEAPON/GetCapabilities
http://wiki.garrysmod.com/page/Entity/ObjectCaps

**Comment by Kefta** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/932
https://github.com/Facepunch/garrysmod-requests/issues/933

Added GetCapabilities hook calls.
